"""initial product schema

Revision ID: 3312a20f5910
Revises: 
Created: 2026-09-01 17:35:52.486299+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3312a20f5910'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('subcategory', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('usage', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('image_path', sa.String(length=1024), nullable=True),
    sa.Column('search_document', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('index_error', sa.Text(), nullable=True),
    sa.Column('has_image_vector', sa.Boolean(), nullable=False),
    sa.Column('has_text_vector', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_products_price_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index('ix_products_brand_price', ['brand', 'price'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index('ix_products_category_price', ['category', 'price'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_colour'), ['colour'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_external_id'), ['external_id'], unique=True)
        batch_op.create_index('ix_products_indexed_at', ['indexed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_subcategory'), ['subcategory'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_subcategory'))
        batch_op.drop_index(batch_op.f('ix_products_price'))
        batch_op.drop_index('ix_products_indexed_at')
        batch_op.drop_index(batch_op.f('ix_products_external_id'))
        batch_op.drop_index(batch_op.f('ix_products_content_hash'))
        batch_op.drop_index(batch_op.f('ix_products_colour'))
        batch_op.drop_index('ix_products_category_price')
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index('ix_products_brand_price')
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    # ### end Alembic commands ###
