"""Render reports/model_report.md from recorded run results.

Generated from reports/run_results.json, which the pipeline writes. No figure in
the report is typed by hand, so it cannot drift from what the code produced.
"""
from __future__ import annotations

from typing import Any

import pandas as pd

from src.config import Config


def _df(x: Any) -> pd.DataFrame:
    return pd.DataFrame(x) if x else pd.DataFrame()


def _md(df: pd.DataFrame, fmt: str = "{:.4f}", cols: list[str] | None = None) -> str:
    if df is None or df.empty:
        return "_no data_"
    d = df.loc[:, [c for c in cols if c in df.columns]] if cols else df.copy()
    for c in d.columns:
        if pd.api.types.is_float_dtype(d[c]):
            d[c] = d[c].map(lambda v: "" if pd.isna(v) else fmt.format(v))
    head = "| " + " | ".join(str(c) for c in d.columns) + " |"
    sep = "|" + "|".join("---" for _ in d.columns) + "|"
    rows = ["| " + " | ".join("" if pd.isna(v) else str(v) for v in r) + " |"
            for r in d.to_numpy()]
    return "\n".join([head, sep, *rows])


def write_report(cfg: Config, r: dict[str, Any]) -> str:
    a_, e_ = r.get("audit", {}), r.get("eda", {})
    t_, c_ = r.get("train", {}), r.get("classical", {})
    i_, s_ = r.get("inventory", {}), r.get("scenarios", {})
    ex = r.get("example_forecast", {})

    L: list[str] = []
    p = L.append

    p("# Model Report — Demand Forecasting & Inventory Optimization\n")
    p("Generated by `python -m src.run report` from `reports/run_results.json`. "
      "Every number is produced by the pipeline.\n")

    p("> **Currency figures are conditional on assumptions.** Only unit value comes "
      "from the data (observed `sell_price`). Margin, holding rate, ordering cost and "
      "the stockout penalty are declared in `configs/config.yaml` and reported in "
      "neutral currency units (CU).\n")

    # ---------------- 1. data ----------------
    p("## 1. Data, grain and quality\n")
    if a_:
        z = a_.get("zeros", {})
        p("- Grain: **SKU x store x day**; target `demand` in units")
        p(f"- Panel: **{a_['n_rows']:,} rows**, {a_['n_series']:,} series, "
          f"{a_['n_days']:,} days ({a_['date_min']} to {a_['date_max']})")
        p(f"- Duplicates on the grain: **{a_['n_duplicate_rows']}**; series with "
          f"internal calendar gaps: **{a_['n_calendar_gaps']}**")
        p(f"- Negative demand: **{a_['n_negative_demand']}**; missing values: "
          f"`{a_['n_missing_values'] or 'none'}`")
        p(f"- Zero share: **{a_['zero_share']:.2%}**, of which "
          f"**{z.get('true_zero_share_of_zeros', 0):.1%}** are true in-life zeros "
          f"({z.get('n_pre_launch_zero', 0):,} pre-launch, "
          f"{z.get('n_post_discontinuation_zero', 0):,} post-delisting)")
        p(f"- Series launching after the panel opens: "
          f"**{a_['n_series_launched_late']:,}**; discontinuation candidates: "
          f"**{a_['n_series_discontinued']:,}**")
        p(f"- Spike days above 20x the series' own non-zero median: "
          f"**{a_['n_spike_days']:,}** across {a_['n_spike_series']:,} series "
          "(kept, not clipped)")
        p("")
        p(f"Demand character: **{a_['intermittent_share']:.1%}** of series are "
          f"Intermittent or Lumpy. `{a_['demand_class_counts']}`\n")
        lk = a_.get("leakage_checks", {})
        p(f"**Leakage probe:** features rebuilt after overwriting every actual past "
          f"the origin — **{lk.get('n_features_checked')} features**, "
          f"{lk.get('n_rows_compared', 0):,} rows, changed: "
          f"`{lk.get('features_changed_by_future_mutation') or 'none'}`, "
          f"**leak-free: {lk.get('leak_free')}**\n")
    p("Full detail in [data_audit.md](./data_audit.md).\n")

    # ---------------- 2. EDA ----------------
    p("## 2. Exploratory findings\n")
    if e_:
        p(f"- Mean demand **{e_['mean_demand']:.3f}** units/series/day; zero share "
          f"**{e_['zero_share']:.2%}**")
        p(f"- Weekday peak **{e_['dow_peak']}**, max/min ratio "
          f"**{e_['dow_ratio_max_min']:.2f}**")
        p(f"- SNAP days lift demand **{e_['snap_lift_pct']:+.1f}%**")
        p(f"- Top 20% of series carry **{e_['share_of_demand_from_top20pct_series']:.1%}** "
          "of demand")
        p(f"- Median SKU sells on only **{e_['median_selling_day_share']:.2f}** of days")
        p(f"- Demand grew **{e_['weekly_growth_first_to_last_8w']:+.1%}** from the "
          "first to the last 8 weeks")
        p("")
        for f in ("01_demand_trend", "02_seasonality", "03_demand_concentration",
                  "04_intermittency", "05_price_and_volatility", "06_demand_classes"):
            p(f"![{f}](./figures/{f}.png)")
        p("")

    # ---------------- 3. validation ----------------
    p("## 3. Validation strategy\n")
    v = cfg["split"]["validation"]
    p(f"Rolling-origin (walk-forward) validation: **{v['n_folds']} folds**, "
      f"{v['horizon_days']}-day horizon, {v['scheme']} window, refitted per fold. "
      f"The held-out test window is the official M5 evaluation period "
      f"**{cfg['split']['test_start']} to {cfg['split']['test_end']}**, never used "
      "for fitting or model selection.\n")
    p("A random split would place day *t+1* in training and day *t* in test for the "
      "same series, letting the model interpolate between days it has already seen "
      "and reporting an accuracy no deployed forecaster can reach.\n")

    # ---------------- 4. model comparison ----------------
    p("## 4. Model comparison\n")
    cols = ["model", "mae", "rmse", "wape", "wape_std", "mase", "bias",
            "skill_vs_seasonal_naive_pct"]
    if t_:
        p("Mean across validation folds:\n")
        p(_md(_df(t_.get("validation_aggregate")), cols=cols))
        p("")
        p("WAPE per fold — a single lucky fold cannot hide here:\n")
        p(_md(_df(t_.get("per_fold_wape"))))
        p("")
        p(f"### Held-out test ({cfg['split']['test_start']} to "
          f"{cfg['split']['test_end']})\n")
        p(_md(_df(t_.get("test_table")),
              cols=["model", "mae", "rmse", "wape", "mase", "bias",
                    "skill_vs_seasonal_naive_pct"]))
        p("")
        p("### Accuracy by horizon\n")
        hb = _df(t_.get("horizon_breakdown"))
        if not hb.empty:
            piv = hb.pivot(index="horizon", columns="model", values="wape").reset_index()
            p(_md(piv))
            p("")
    if c_:
        p("### Classical models (ETS, SARIMA) on a stratified sample\n")
        p(f"Fitted per series on **{c_.get('n_series')} of "
          f"{a_.get('n_series', '?')}** series. Fit failures: `{c_.get('n_failed')}`.\n")
        p(_md(_df(c_.get("table")),
              cols=["model", "mae", "rmse", "wape", "mase", "bias"]))
        p("")
        for n in c_.get("notes", []):
            p(f"- {n}")
        p("")

    p("### Why MAPE is not reported\n")
    p(f"With **{a_.get('zero_share', 0):.0%}** of observations equal to zero, MAPE is "
      "undefined on most rows. WAPE is the headline because it only needs aggregate "
      "demand to be non-zero. MASE is reported for scale-free comparison, with one "
      "caveat visible in the tables: **the `zero` baseline attains the best MASE**, "
      "because averaging per-row scaled errors rewards predicting nothing on sparse "
      "series. WAPE correctly assigns it a score of 1.0.\n")

    # ---------------- 5. segmentation ----------------
    p("## 5. Demand segmentation and per-segment model choice\n")
    if t_:
        p(t_.get("classification_note", ""))
        p("")
        p(_md(_df(t_.get("segment_summary")),
              cols=["demand_class", "series", "series_share", "demand_share",
                    "mean_daily_demand", "median_ADI", "median_CV2",
                    "mean_zero_share"]))
        p("")
        p("**Which model wins where** — the answerable version of \"which model is "
          "best\":\n")
        p(_md(_df(t_.get("best_per_segment")),
              cols=["demand_class", "n", "best_model", "best_wape", "best_baseline",
                    "baseline_wape", "improvement_pct"]))
        p("")
        bp = _df(t_.get("best_per_segment"))
        if not bp.empty and "improvement_pct" in bp.columns:
            wins = bp[bp["improvement_pct"].fillna(0) < 0.5]["demand_class"].tolist()
            if wins:
                p(f"On **{', '.join(map(str, wins))}** series the ML model does not "
                  "beat the best baseline by any operationally meaningful margin. "
                  "Recommended approach per segment is in "
                  "`src/evaluation/segmentation.py::SEGMENT_ADVICE`.\n")

    # ---------------- 6. error analysis ----------------
    p("## 6. Error analysis\n")
    if t_:
        p("Spearman correlation between series characteristics and series WAPE:\n")
        p(_md(_df(t_.get("error_drivers"))))
        p("")
        p("Accuracy on SNAP (promotion-like) days versus other days:\n")
        p(_md(_df(t_.get("promo_errors"))))
        p("")
        p("Hardest series (highest WAPE, restricted to series with enough demand to "
          "be meaningful):\n")
        p(_md(_df(t_.get("worst_series")).head(10),
              cols=["series_id", "demand_class", "volume_class", "total_actual",
                    "wape", "bias", "zero_share", "cv_demand", "weekly_strength"]))
        p("")
        p("Top features by LightGBM gain:\n")
        p(_md(_df(t_.get("feature_importance")).head(12), fmt="{:.0f}"))
        p("")

    # ---------------- 7. uncertainty ----------------
    p("## 7. Forecast uncertainty\n")
    if t_:
        ir = _df(t_.get("interval_report"))
        if not ir.empty:
            p("P10-P90 interval from LightGBM quantile regression, nominal coverage "
              "80%:\n")
            p(_md(ir, cols=["n", "nominal_coverage", "empirical_coverage",
                            "coverage_gap", "mean_interval_width",
                            "pinball_q10", "pinball_q50", "pinball_q90"]))
            p("")
            gap = float(ir["coverage_gap"].iloc[0])
            p(f"Empirical coverage is **{float(ir['empirical_coverage'].iloc[0]):.2%}** "
              f"against a nominal 80% — a gap of **{gap:+.2%}**. The interval is "
              "therefore somewhat too narrow, which matters because safety stock is "
              "sized from the upper tail. Reporting the gap is the point: an "
              "unvalidated P90 is an assumption dressed as a measurement.\n")
            p("Two further honesty notes. Demand is zero-inflated, so an exact nominal "
              "coverage is not attainable with a discrete, floored-at-zero target. And "
              "interval width does not grow monotonically with horizon, so the "
              "intervals are not fully conditioning on distance.\n")

    # ---------------- 8. inventory ----------------
    p("## 8. Inventory optimization\n")
    if i_:
        p(f"Protection window = **{i_['protection_days']} days** "
          f"({i_['lead_time_days']} lead + {i_['review_period_days']} review). Under "
          "periodic review the exposure is lead time **plus** the review period; "
          "omitting the review period systematically under-protects.\n")
        p("Safety stock is derived from the spread of **lead-time forecast error**, "
          "not from historical demand variability. That is the whole reason "
          "forecasting has value here: a better forecast shrinks the error spread and "
          "therefore the stock required. Sizing from demand variability would return "
          "the same answer no matter how good the forecast is.\n")
        p(f"- lead-time error windows per series (median): "
          f"**{i_['median_error_windows_per_series']}**")
        p(f"- mean safety stock at {i_['service_level']:.0%}: normal "
          f"**{i_['mean_ss_normal']:.2f}** units, empirical quantile "
          f"**{i_['mean_ss_empirical']:.2f}** units (median ratio "
          f"**{i_['median_ss_ratio']:.3f}**)\n")
        p("### Baseline vs forecast-driven policy, simulated on the held-out 28 days\n")
        p(_md(_df(i_.get("policy_comparison")),
              cols=["policy", "total_demand", "units_short", "fill_rate",
                    "cycle_service_level", "avg_inventory_units", "orders_placed",
                    "series_with_stockout"]))
        p("")
        p(_md(_df(i_.get("cost_comparison")), fmt="{:.2f}",
              cols=["policy", "holding_cost_cu", "stockout_cost_cu",
                    "ordering_cost_cu", "total_cost_cu", "fill_rate"]))
        p("")
        p(f"Best policy by total cost: **{i_.get('best_policy')}**. Median inventory "
          f"coverage **{i_.get('median_coverage_days', 0):.1f} days**.\n")
        p("### Highest stockout risk — the operational watch list\n")
        p(_md(_df(i_.get("risk_table")).head(10), fmt="{:.3f}",
              cols=["series_id", "demand_class", "volume_class", "total_demand",
                    "units_short", "shortfall_share", "fill_rate", "reorder_point"]))
        p("")

    # ---------------- 9. scenarios ----------------
    p("## 9. Service-level scenarios and the economic optimum\n")
    if s_:
        p(_md(_df(s_.get("scenario_table")),
              cols=["service_level", "z", "mean_safety_stock", "achieved_fill_rate",
                    "achieved_cycle_sl", "units_short", "avg_inventory_units",
                    "holding_cost_cu", "stockout_cost_cu", "total_cost_cu",
                    "is_cost_minimum"]))
        p("")
        nv = s_.get("newsvendor", {})
        p(f"Simulated cost-minimum service level: "
          f"**{s_.get('cost_optimal_service_level', 0):.0%}**. The newsvendor critical "
          f"ratio Cu/(Cu+Co) is **{nv.get('critical_ratio_mean', 0):.4f}** "
          f"(Cu {nv.get('cu_mean_cu', 0):.3f} CU vs Co {nv.get('co_mean_cu', 0):.4f} "
          "CU). The closed form and the simulation agree, which is the point of "
          "computing both.\n")
        p("### Sensitivity: the recommendation depends on the assumptions\n")
        p(_md(_df(s_.get("sensitivity")),
              cols=["stockout_penalty_multiplier", "cost_optimal_service_level",
                    "total_cost_cu", "achieved_fill_rate", "avg_inventory_units"]))
        p("")

    # ---------------- 10. example ----------------
    if ex:
        p("## 10. Example forecast and reorder recommendation\n")
        p("```json")
        import json as _json
        p(_json.dumps({k: v for k, v in ex.items() if k != "forecast_head"}, indent=2))
        p("```\n")
        p(_md(_df(ex.get("forecast_head")), fmt="{:.3f}"))
        p("")

    # ---------------- 11. limitations ----------------
    p("## 11. Limitations\n")
    p("- **The economics are assumptions.** Only unit value is measured. The "
      "cost-optimal service level moves with the stockout penalty, as the "
      "sensitivity table shows.")
    p("- **Subset, not the full panel.** 600 of 30,490 series, stratified over "
      "category and demand class with a fixed seed. Absolute accuracy would differ "
      "on the full data; the ranking of methods is the transferable result.")
    p("- **Named holiday events are absent** from this mirror; holiday flags are "
      "derived from pandas' US federal calendar, which misses retail-specific events.")
    p("- **Price and promo for the target date are assumed known.** True for a "
      "planned promo calendar, false for reactive competitor pricing.")
    p("- **Prediction intervals under-cover** (see section 7), so quantile-based "
      "safety stock is slightly optimistic.")
    p("- **Lead time is deterministic.** Real lead times vary, and lead-time variance "
      "usually contributes more to required safety stock than demand variance does.")
    p("- **Lost sales, not backorders**, and demand is assumed observed — but a "
      "stockout censors demand, so the recorded target understates true demand for "
      "exactly the series that stocked out.")
    p("- **ETS and SARIMA were fitted on a sample** and are compared against "
      "baselines on that same sample, not against the global ML model on all series.\n")

    p("## 12. Future improvements\n")
    p("- Model **censored demand** explicitly, since observed sales understate demand "
      "during stockouts.")
    p("- Add **stochastic lead time**, which typically dominates demand uncertainty in "
      "safety-stock sizing.")
    p("- Fit **per-segment models** rather than one global model, given that the "
      "segment analysis shows baselines winning on the intermittent majority.")
    p("- Use **hierarchical reconciliation** across SKU / department / store so store "
      "and category forecasts are coherent with item forecasts.")
    p("- Replace quantile regression with **conformal prediction** for coverage "
      "guarantees that hold without distributional assumptions.\n")

    dest = cfg.resolve("paths", "reports_dir") / "model_report.md"
    dest.write_text("\n".join(L), encoding="utf-8")
    return str(dest)
