"""Render reports/model_report.md from the recorded run results.

The report is generated from reports/run_results.json, which is written by the
pipeline itself. No figure in it is typed by hand, so it cannot drift from what
the code actually produced.
"""
from __future__ import annotations

from typing import Any

import pandas as pd

from src.config import Config


def _df(records: Any) -> pd.DataFrame:
    return pd.DataFrame(records) if records else pd.DataFrame()


def _md(df: pd.DataFrame, floatfmt: str = "{:.4f}") -> str:
    if df.empty:
        return "_no data_"
    out = df.copy()
    for c in out.columns:
        if pd.api.types.is_float_dtype(out[c]):
            out[c] = out[c].map(lambda v: "" if pd.isna(v) else floatfmt.format(v))
    header = "| " + " | ".join(str(c) for c in out.columns) + " |"
    sep = "|" + "|".join("---" for _ in out.columns) + "|"
    rows = ["| " + " | ".join(str(v) for v in r) + " |" for r in out.to_numpy()]
    return "\n".join([header, sep, *rows])


def write_report(cfg: Config, results: dict[str, Any]) -> str:
    """Compose and write the model report."""
    audit = results.get("audit", {})
    eda = results.get("eda", {})
    tr = results.get("train", {})
    ex = results.get("explain", {})
    example = results.get("example_prediction", {})

    econ = cfg["economics"]
    L: list[str] = []
    a = L.append

    a("# Model Report — Customer Churn Prediction & Explainable ML\n")
    a("Generated by `python -m src.run report` from `reports/run_results.json`. "
      "Every number is produced by the pipeline; none is typed by hand.\n")

    # ---------------- headline ----------------
    a("## Headline\n")
    if tr:
        cmp = tr.get("paired_comparison", {})
        stab = _df(tr.get("stability"))
        a(f"- Best model by cross-validated PR-AUC: **{tr['best_model']}** "
          f"(PR-AUC {cmp.get('mean_a', float('nan')):.4f}).")
        a(f"- It beats an **untuned logistic regression** by only "
          f"{cmp.get('difference', 0):+.4f} PR-AUC "
          f"({cmp.get('difference_in_sd', 0):.2f} pooled SD), "
          f"paired t-test p={cmp.get('ttest_p', 1):.3f} — **not significant**. "
          "On this dataset gradient boosting does not earn its complexity on "
          "discrimination alone.")
        if not stab.empty:
            a(f"- The designated test split is the **weakest of {len(stab)} folds** "
              f"(PR-AUC {stab.loc[0, 'pr_auc']:.4f} vs across-fold mean "
              f"{stab['pr_auc'].mean():.4f}, sd {stab['pr_auc'].std():.4f}). "
              "The split was **not re-drawn** to improve the number.")
        a(f"- Calibration selected: **{tr.get('calibration_selected')}** — the model "
          "was already well calibrated, so a calibrator was only adopted if it "
          f"cleared a pre-declared Brier gain of {cfg['calibration']['min_brier_gain']}.")
        thr = tr.get("threshold", {})
        a(f"- Value-optimal threshold **{thr.get('best', 0):.2f}**, not 0.5, because a "
          "missed churner costs far more than a wasted contact under the assumed "
          "economics.")
        a(f"- A **per-customer expected-value rule** returns "
          f"{thr.get('per_customer_net_value', 0):,.0f} CU from "
          f"{thr.get('per_customer_contacts', 0)} contacts, against "
          f"{thr.get('net_value', 0):,.0f} CU for the best single global threshold.")
    a("")

    a("> **All currency figures are conditional on assumptions.** The dataset "
      "contains no campaign costs, offer values or intervention outcomes, so the "
      "retention economics in `configs/config.yaml` are declared inputs, not "
      "measurements. Figures use neutral **currency units (CU)**. They are not a "
      "claim about a real business.\n")

    # ---------------- data ----------------
    a("## 1. Data and target\n")
    if audit:
        a(f"- Rows: **{audit['n_rows']:,}**; churn rate **{audit['churn_rate']:.2%}** "
          f"(~1:{(1 - audit['churn_rate']) / audit['churn_rate']:.2f} imbalance).")
        a("- Target: `Churn == 'Yes'`.")
        a(f"- Missing (including whitespace-only cells): `{audit['missing']}`. "
          "`TotalCharges` is published as text; its 11 blanks all have `tenure == 0`, "
          "so the value is structurally absent, not missing at random, and is set to 0.")
        a(f"- Duplicates: {audit['n_exact_duplicates']} exact, "
          f"{audit['n_id_duplicates']} duplicate ids, "
          f"{audit['n_feature_duplicates']} feature-identical.")
        a(f"- **{audit['n_conflicting_label_rows']} rows in "
          f"{audit['n_conflicting_groups']} groups are feature-identical with "
          f"contradictory labels** — irreducible label noise "
          f"({audit['label_noise_rate']:.2%} of rows).")
        a(f"- Train/test contamination after group-aware splitting: "
          f"**{audit['contamination_overlap']}**.")
        a(f"- Invalid ranges: `{audit['invalid_values'] or 'none'}`; unexpected "
          f"categories: `{audit['invalid_categories'] or 'none'}`; structural "
          f"inconsistencies: `{audit['structural_inconsistencies'] or 'none'}`.")
    a("\nFull detail in [data_audit.md](./data_audit.md).\n")

    a("### Leakage audit\n")
    if audit:
        sfa = audit.get("single_feature_auc", {})
        top = list(sfa.items())[:6]
        a("Each feature scored alone under 5-fold stratified CV. A feature "
          "approaching AUC 1.0 would be the target in disguise.\n")
        a(_md(pd.DataFrame(top, columns=["feature", "cv_roc_auc_alone"])))
        a("")
        a(f"**Leakage suspects: {audit.get('leakage_suspects') or 'none'}.** The "
          "strongest single feature is a genuine commercial predictor, not an outcome.")
        a(f"\n`TotalCharges` regressed on `tenure x MonthlyCharges` gives "
          f"**R² = {audit['total_charges_r2']:.4f}** — redundancy, not leakage. The "
          "engineered `billing_discrepancy` uses the residual instead of restating it.")
        a("\n**Limitation:** the dataset is one snapshot with no event timestamps, so "
          "no out-of-time split and no empirical post-churn test are possible. "
          "Post-churn risk is assessed per column from semantics.\n")

    # ---------------- eda ----------------
    a("## 2. EDA findings\n")
    if eda:
        a(f"- Overall churn (train): **{eda['overall_churn_rate']:.2%}**.")
        a(f"- Churn is heavily front-loaded: **{eda['churn_first_6m']:.1%}** in the "
          f"first 6 months against **{eda['churn_last_band']:.1%}** at 49–72 months.")
        a(f"- Month-to-month + 0–6 months is both the highest-risk and "
          f"highest-volume cell: **{eda['m2m_first6m_churn']:.1%}** churn across "
          f"**{eda['m2m_first6m_customers']:,}** customers.")
        a(f"- Electronic check churns at **{eda['electronic_check_churn']:.1%}**; "
          f"fibre at **{eda['fiber_churn']:.1%}**.")
        a(f"- Median monthly charge: **{eda['median_monthly_churned']:.2f}** for "
          f"churners vs **{eda['median_monthly_stayed']:.2f}** for stayers.")
        addons = eda.get("churn_by_n_addons", {})
        if addons:
            keys = sorted(addons, key=lambda k: int(float(k)))
            a(f"- Add-on adoption is monotonically protective: churn falls from "
              f"**{addons[keys[0]]:.1%}** at {keys[0]} add-ons to "
              f"**{addons[keys[-1]]:.1%}** at {keys[-1]}.")
        a("\n![churn overview](./figures/01_churn_overview.png)")
        a("![tenure](./figures/02_churn_by_tenure.png)")
        a("![contract and payment](./figures/03_churn_by_contract_payment.png)")
        a("![services](./figures/04_churn_by_services.png)")
        a("![distributions](./figures/05_numeric_distributions.png)")
        a("![risk concentration](./figures/06_risk_concentration.png)\n")

    # ---------------- features ----------------
    a("## 3. Engineered features\n")
    from src.features.engineer import FEATURE_DOCS
    a("All features are **row-wise**, so they depend only on the customer's own "
      "values. That is what makes them safe to compute before the split and "
      "identical at inference. No target encoding or dataset-level aggregate is used.\n")
    a("| feature | type | why it should help |")
    a("|---|---|---|")
    for name, (kind, why) in FEATURE_DOCS.items():
        a(f"| `{name}` | {kind} | {why} |")
    a("")

    # ---------------- models ----------------
    a("## 4. Model comparison\n")
    if tr:
        comp = _df(tr.get("comparison"))
        if not comp.empty:
            cols = ["model", "tuned", "pr_auc", "pr_auc_std", "roc_auc", "f1",
                    "recall", "precision", "brier"]
            a("Cross-validated on the training split with group-aware "
              f"`StratifiedGroupKFold` (k={cfg['split']['cv_folds']}), tuned on "
              f"`{cfg['models']['scoring']}`.\n")
            a(_md(comp.loc[:, [c for c in cols if c in comp.columns]]))
            a("")
        a(f"Best hyperparameters (`{tr['best_model']}`): `{tr.get('best_params')}`\n")
        cmp = tr.get("paired_comparison", {})
        a("### Does the complex model earn its place?\n")
        a(f"Paired across identical folds: **{cmp.get('model_a')}** "
          f"{cmp.get('mean_a', 0):.4f} vs **{cmp.get('model_b')}** "
          f"{cmp.get('mean_b', 0):.4f}, difference {cmp.get('difference', 0):+.4f} "
          f"({cmp.get('difference_in_sd', 0):.2f} pooled SD). "
          f"Paired t p={cmp.get('ttest_p', 1):.4f}, Wilcoxon p="
          f"{cmp.get('wilcoxon_p', 1):.4f} → "
          f"**significant: {cmp.get('significant_at_05')}**.\n")
        a("With five folds the test has low power, so this means *the data cannot "
          "distinguish them*, not that they are proven equal. The honest reading: "
          "logistic regression is a legitimate production choice here, trains in "
          "~2s against ~16s, and is inherently interpretable. The boosted model is "
          "retained mainly because `TreeExplainer` gives exact SHAP values.\n")

        stab = _df(tr.get("stability"))
        if not stab.empty:
            a("### Split stability\n")
            a("Each fold used in turn as the held-out test set, to show how much of a "
              "single split's score is luck.\n")
            a(_md(stab))
            a(f"\nSpread across folds is **{stab['pr_auc'].max() - stab['pr_auc'].min():.4f}** "
              f"PR-AUC. Fold 0 is the designated test set and the weakest of the "
              f"{len(stab)}; it was not re-drawn. Treat "
              f"**{stab['pr_auc'].mean():.4f} ± {stab['pr_auc'].std():.4f}** as the "
              "more reliable estimate and the single-split figure as conservative.\n")

    # ---------------- calibration ----------------
    a("## 5. Probability calibration\n")
    a("Retention decisions multiply probability by customer value, so the "
      "probabilities must mean what they say. A model that ranks well but is "
      "miscalibrated by 2x inflates every expected-value calculation and spends "
      "real budget against an imagined return.\n")
    if tr:
        cal = _df(tr.get("calibration"))
        if not cal.empty:
            a(_md(cal.loc[:, ["method", "brier", "ece", "log_loss", "pr_auc"]]))
            a("")
        a(f"Selected: **{tr.get('calibration_selected')}**. Calibrators are fitted "
          "with internal CV on the training split only and judged on the untouched "
          "test set.\n")
        a("`ece` is reported next to Brier because the Brier score mixes calibration "
          "and discrimination, so it can improve for the wrong reason.\n")

    # ---------------- evaluation ----------------
    a("## 6. Evaluation and threshold selection\n")
    a("### Why accuracy is not the headline\n")
    if audit:
        a(f"Predicting 'nobody churns' scores **{1 - audit['churn_rate']:.2%} accuracy** "
          "and finds zero churners. Accuracy also presumes a 0.5 cutoff, which no "
          "retention campaign would choose.\n")
    if tr:
        md, mt = tr.get("metrics_default", {}), tr.get("metrics_tuned", {})
        rows = pd.DataFrame([md, mt])
        if not rows.empty:
            cols = ["threshold", "roc_auc", "pr_auc", "precision", "recall", "f1",
                    "accuracy", "brier", "log_loss", "tn", "fp", "fn", "tp"]
            a(_md(rows.loc[:, [c for c in cols if c in rows.columns]]))
            a("")
        thr = tr.get("threshold", {})
        a("### Cost/value framework\n")
        a(f"```\nEV(contact) = p x success_rate x value - (contact_cost + incentive_cost)\n"
          f"\ncontact_cost   = {econ['contact_cost']} CU      (assumed)\n"
          f"incentive_cost = {econ['incentive_cost']} CU     (assumed)\n"
          f"success_rate   = {econ['success_rate']}        (assumed)\n"
          f"value          = MonthlyCharges x {econ['horizon_months']} months\n```\n")
        a("| policy | net value (CU) | contacts |")
        a("|---|---:|---:|")
        a("| contact nobody | 0 | 0 |")
        a(f"| contact everyone | {thr.get('contact_all', 0):,.0f} | all |")
        a(f"| best global threshold ({thr.get('best', 0):.2f}) | "
          f"{thr.get('net_value', 0):,.0f} | — |")
        a(f"| **per-customer EV rule** | **{thr.get('per_customer_net_value', 0):,.0f}** | "
          f"{thr.get('per_customer_contacts', 0)} |")
        a("")
        a(f"The per-customer rule wins because the break-even probability varies with "
          f"customer value, from **{thr.get('breakeven_min', 0):.1%}** to "
          f"**{thr.get('breakeven_max', 0):.1%}** across the test set. A single global "
          "cut cannot express that a high-value customer is worth contacting at much "
          "lower risk than a low-value one.\n")

        sens = _df(tr.get("sensitivity"))
        if not sens.empty:
            a("### Sensitivity to the assumptions\n")
            a("The optimal threshold is a function of parameters the data cannot "
              "supply, so a single threshold presented as *the* answer would hide "
              "that dependency.\n")
            a(_md(sens.loc[:, ["success_rate", "incentive_cost", "best_threshold",
                               "net_value", "contact_rate", "precision", "recall"]],
                  floatfmt="{:.3f}"))
            a("")

    # ---------------- segmentation ----------------
    a("## 7. Risk segmentation\n")
    if tr:
        seg = _df(tr.get("segments"))
        if not seg.empty:
            keep = [c for c in ["risk_segment", "customers", "share_of_customers",
                                "avg_predicted_risk", "realised_churn_rate",
                                "share_of_churners", "avg_customer_value",
                                "recommended_action"] if c in seg.columns]
            a("Bands are **validated**, not merely declared: realised churn on the "
              "test set is reported beside predicted risk.\n")
            a(_md(seg.loc[:, keep]))
            a("")
        v = tr.get("segment_validation", {})
        if v:
            a(f"- Realised churn rises monotonically across bands: "
              f"**{v.get('monotonic_realised_churn')}**.")
            a(f"- Largest gap between mean predicted risk and realised churn: "
              f"**{v.get('max_abs_calibration_gap', 0):.4f}**.")
            a(f"- Top band churns **{v.get('lift_top_vs_bottom', 0):.1f}x** the "
              "bottom band.\n")

    a("## 8. Business decision framework\n")
    a("Risk alone is not a decision. The rule combines risk band with customer value "
      "and gates every action on an expected-value test.\n")
    if tr:
        camp = _df(tr.get("campaign"))
        if not camp.empty:
            keep = [c for c in ["risk_segment", "value_tier", "customers", "avg_risk",
                                "avg_value_cu", "contacts", "expected_value_cu",
                                "priority"] if c in camp.columns]
            a(_md(camp.loc[:, keep], floatfmt="{:.2f}"))
            a("")
        a(f"Contacts recommended: **{tr.get('n_contacts')}** of "
          f"{tr.get('n_test')} test customers. In **{tr.get('n_ev_overrides')}** cases "
          "the expected-value test recommends contact for a customer in a "
          "Low/Medium band — the value dimension overriding the risk band, which a "
          "one-dimensional 'contact high risk' rule cannot do.\n")
    from src.inference.decision import ACTION_MATRIX
    a("| risk band | value tier | action | priority |")
    a("|---|---|---|---:|")
    for (band, tier), (action, priority, _ch) in sorted(
            ACTION_MATRIX.items(), key=lambda kv: kv[1][1]):
        a(f"| {band} | {tier} | {action} | {priority} |")
    a("")

    # ---------------- explainability ----------------
    a("## 9. Explainable ML (SHAP)\n")
    if ex:
        gi = _df(ex.get("grouped_importance"))
        if not gi.empty:
            a("Importance aggregated back to business features, because one-hot "
              "encoding splits one concept across several columns and understates it.\n")
            a(_md(gi.head(12)))
            a("")
        ci = _df(ex.get("concept_importance"))
        if not ci.empty:
            a("Aggregated further to business **concepts**, using the same grouping as "
              "the per-customer explanations so the global and local views agree. "
              "`Contract` and `is_month_to_month` are one commercial fact, not two "
              "drivers.\n")
            a(_md(ci))
            a("")
        a("![shap summary](./figures/07_shap_summary.png)")
        a("![grouped importance](./figures/08_shap_importance_grouped.png)\n")

        reps = ex.get("representatives", {})
        if reps:
            a("### Representative customers\n")
            a("Contributions are in **log-odds** and are not additive in probability; "
              "they rank *why* a customer scored as they did.\n")
            for band, r in reps.items():
                a(f"**{band}** — predicted churn **{r['probability']:.1%}** "
                  f"({r['contract']}, tenure {r['tenure']}m, "
                  f"{r['monthly_charges']:.2f}/month)\n")
                a("Increases risk:\n")
                for f in r.get("top_risk_factors", []):
                    a(f"- {f['reason']} ({f['contribution']:+.3f})")
                prot = r.get("top_protective_factors", [])
                if prot:
                    a("\nReduces risk:\n")
                    for f in prot:
                        a(f"- {f['reason']} ({f['contribution']:+.3f})")
                a(f"\n![{band}](./figures/{r['figure']})\n")

    # ---------------- errors ----------------
    a("## 10. Error analysis\n")
    if tr:
        prof = _df(tr.get("error_profile"))
        if not prof.empty:
            a("Mean feature values by outcome class at the operating threshold.\n")
            a(_md(prof, floatfmt="{:.2f}"))
            a("")
        c = tr.get("error_costs", {})
        if c:
            a(f"- False negatives: **{c['n_false_negative']}**, ~"
              f"{c['mean_fn_cost_cu']:.0f} CU each in forgone saving.")
            a(f"- False positives: **{c['n_false_positive']}**, "
              f"{c['mean_fp_cost_cu']:.0f} CU each in wasted spend.")
            a(f"- Cost ratio **{c['cost_ratio_fn_to_fp']:.1f}:1** (FN:FP).\n")
        note = tr.get("threshold_note")
        if note:
            a(f"{note}\n")
        ln = tr.get("label_noise", {})
        if ln:
            a(f"Observed error rate **{ln['observed_error_rate']:.4f}** against an "
              f"irreducible floor of ~**{ln['irreducible_floor_estimate']:.4f}** from "
              "label conflicts. Most error is therefore genuine model limitation, not "
              "data noise — but the floor is not zero.\n")

    a("## 11. Segment-level performance and fairness\n")
    if tr:
        disp = _df(tr.get("disparities"))
        if not disp.empty:
            keep = [c for c in ["attribute", "segment", "n", "churn_rate", "roc_auc",
                                "pr_auc", "recall", "precision", "calibration_gap"]
                    if c in disp.columns]
            a(_md(disp.loc[:, keep]))
            a("")
        sp = tr.get("spreads", {})
        if sp:
            worst = sorted(sp.items(), key=lambda kv: -kv[1])[:6]
            a("Largest performance spreads within an attribute:\n")
            a(_md(pd.DataFrame(worst, columns=["measure", "spread"])))
            a("")
        a("Read these as **stability and coverage checks**, not a fairness "
          "certification. `gender` is included because a large spread there would be "
          "a warning sign; a small spread is not evidence of fairness in any broader "
          "sense, and this dataset has no protected attributes beyond gender and "
          "senior-citizen status.\n")

    # ---------------- example ----------------
    if example:
        a("## 12. Example prediction\n")
        a("Produced by `python -m src.run predict`.\n")
        a("```json")
        import json as _json
        a(_json.dumps(example, indent=2)[:2600])
        a("```\n")

    a("## 13. Limitations\n")
    a("- **Snapshot data, no timestamps.** No out-of-time validation, so the estimate "
      "assumes the future resembles a random sample of the past. For a churn model "
      "this is the single largest caveat: real deployments degrade as pricing, "
      "competitors and product mix change.")
    a("- **The economics are assumptions.** Every CU figure is conditional on "
      "`configs/config.yaml`. The sensitivity table shows the optimal threshold moves "
      "with them.")
    a("- **A single 80/20 split is noisy at this size** — spread across folds is "
      "material, and the designated test fold is the weakest.")
    a("- **The boosted model is not significantly better** than untuned logistic "
      "regression on this data.")
    if audit:
        a(f"- **{audit.get('n_conflicting_label_rows', 0)} rows carry contradictory "
          "labels**, so perfect accuracy is unreachable.")
    a("- **`Churn` is defined as 'left within the last month'** with no reason code, "
      "so voluntary and involuntary churn are pooled. They need different "
      "interventions, and the model cannot separate them.")
    a("- **SHAP contributions are log-odds and correlation-aware, not causal.** "
      "`Contract` being the strongest driver does not establish that moving a "
      "customer onto a two-year contract causes retention; customers who accept long "
      "contracts differ systematically. Only an experiment can answer that.\n")

    a("## 14. Future improvements\n")
    a("- Obtain event-level history with timestamps to enable out-of-time validation "
      "and survival modelling (time-to-churn rather than a binary snapshot).")
    a("- Run a randomised retention holdout to *measure* `success_rate` and offer "
      "uplift instead of assuming them, which would turn the EV layer into a real "
      "financial model.")
    a("- Move from churn prediction to **uplift modelling**: the decision should "
      "target customers whose behaviour the intervention changes, not those most "
      "likely to leave regardless.")
    a("- Add drift monitoring on input distributions and calibration, since a churn "
      "model's economics decay silently.")
    a("- Capture churn reason codes to separate voluntary from involuntary churn.\n")

    dest = cfg.resolve("paths", "reports_dir") / "model_report.md"
    dest.write_text("\n".join(L), encoding="utf-8")
    return str(dest)
